import type { Cepheid } from '../types/api';

export const MOCK_CEPHEIDS: Cepheid[] = [
	{
		id:          "1",
		img:         "/img/Zvezda-Delta-TSefeya.jpg",
		title:       "Дельта Цефея Mock",
		period:      5.366341,
		source:      "ESA Gaia Mission",
		description: "Прототип цефеид, двойная система с периодом 5.366 дней",
	},
	{
		id:          "2",
		img:         "/img/RSPuppis.jpg",
		title:       "RS Кормы",
		period:      41.3876,
		source:      "NASA Hubble Space Telescope",
		description: "Одна из самых ярких галактических цефедий с точными данными от Gaia",
	},
	{
		id:          "3",
		img:         "/img/Polyarnaya-zvezda.jpg",
		title:       "Полярная звезда (Polaris)",
		period:      3.9716,
		source:      "European Space Agency (ESA)",
		description: "Ближайшая к Земле цефеида, демонстрирующая изменения амплитуды пульсаций",
	},
	{
		id:          "4",
		img:         "/img/default-star.jpg",
		title:       "RT Возничего",
		period:      3.728,
		source:      "NASA/ESA Hubble Space Telescope",
		description: "Цефеида в созвездии Возничего",
	},
	{
		id:          "5",
		img:         "/img/default-star.jpg",
		title:       "V1 в Туманности Андромеды",
		period:      31.4,
		source:      "NASA Hubble Heritage Team",
		description: "Исторически важная цефеида, использованная Эдвином Хабблом для доказательства существования других галактик",
	},
	// {
	// 	id:          "6",
	// 	img:         "/img/Altair.jpg",
	// 	title:       "Эта Орла",
	// 	period:      7.176,
	// 	source:      "American Association of Variable Star Observers (AAVSO)",
	// 	description: "Яркая цефеида в созвездии Орла, видимая невооруженным глазом",
	// },
	// {
	// 	id:          "7",
	// 	img:         "/img/Beta-Ribi.jpg",
	// 	title:       "Бета Золотой Рыбы",
	// 	period:      9.842,
	// 	source:      "European Southern Observatory (ESO)",
	// 	description: "Яркая цефеида в Большом Магеллановом Облаке",
	// },
	// {
	// 	id:          "8",
	// 	img:         "/img/Zeta_Geminorum.jpg",
	// 	title:       "ζ Близнецов",
	// 	period:      10.150,
	// 	source:      "Gaia Data Release 3 (DR3)",
	// 	description: "Цефеида с хорошо изученным периодом и светимостью",
	// },
	// {
	// 	id:          "9",
	// 	img:         "/img/default-star.jpg",
	// 	title:       "W Девы",
	// 	period:      17.27,
	// 	source:      "NASA/ESA Hubble Key Project",
	// 	description: "Прототип цефеид типа II (более старые население II звезды)",
	// },
	// {
	// 	id:          "10",
	// 	img:         "/img/Alfa-Lisichki.jpg",
	// 	title:       "SV Лисички",
	// 	period:      45.0,
	// 	source:      "Gaia Space Observatory",
	// 	description: "Долгопериодическая цефеида с точными параллаксами от Gaia",
	// },
];